// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qmitdcmdeizsyvptkznp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFtaXRkY21kZWl6c3l2cHRrem5wIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM5NDE5MjUsImV4cCI6MjA1OTUxNzkyNX0.Z1j1mWviziiebDb5Ef1nTC6WVzxLjTS1uynlH3-t1cc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);